### ISSUE TITLE
Move Relaton `version` into an input variable

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/github-action-build-relaton-yaml-source#1]
https://github.com/ietf-ribose/github-action-build-relaton-yaml-source/blob/84abfac798a41ae5a96a49ddc74e10179e2cba77/action.yml#L19

**Comment by ronaldtse** [comment]
@strogonoff It is possible to make it an option with a default, allowing specific repo overrides.

**Comment by strogonoff** [comment]
> @strogonoff It is possible to make it an option with a default, allowing specific repo overrides.

I’m not understanding. This action is exclusively designed for one purpose: building data repositories for ingestion by IETF BibXML service. It was created specifically to ensure all source repositories in use by IETF BibXML service use the exact same YAML structure (indicated by `relaton-cli` version), readable by the service in production. There is no scenario in which some data repositories would use YAML structure incompatible with IETF BibXML service.

**Comment by strogonoff** [comment]
The purpose is indicated in README. If we need a general-purpose action, this could be another action udner `riboseinc`, and this action can depend on _that_ action, but _this_ action must have the version pinned and any option to override it goes counter to this action’s purpose.
