### ISSUE TITLE
Move to `ietf-tools`

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/github-action-build-relaton-yaml-source#5]
Before we make `relaton-data-*` repositories depend on this, perhaps it makes sense to move the action under ietf-tools to avoid having to make another change?

**Comment by strogonoff** [comment]
cc @kesara — this action will be used to avoid having to change GHA workflow in each data repository when bibliographic data generator version needs to be updated (with supervision) to let BibXML service take advantage of newer bibliographic data schema without causing regressions.

Instead of the current state where each data repository references a Ruby gem without pinning it to a version, data repositories will reference the latest/HEAD version of this action, and the action will specify the gem with version pinned down to minor component. Thereafter, changing gem version _in this action_ will cause all data repositories to be built using that version with corresponding schema (and conversely unless the version is updated no breaking schema change would occur).

**Comment by ronaldtse** [comment]
Once we get conformation from @kesara we can move the repository.

**Comment by strogonoff** [comment]
An example of a repository using this action: https://github.com/ietf-ribose/relaton-data-nist/blob/main/.github/workflows/fetcher.yml. (This is a fork in `ietf-ribose` organization, the change was not applied in `ietf-tools` yet. Per this issue I think we should move the action to `ietf-tools` before applying this change to upstream repositories in `ietf-tools`.)

**Comment by kesara** [comment]
@strogonoff, @ronaldtse I'm happy to move this repository to ietf-tools now.

**Comment by kesara** [comment]
I have transfered the repository.
@strogonoff, @ronaldtse and `@andrew2net` have write access to the repository.

**Comment by strogonoff** [comment]
Thanks!

**Comment by ronaldtse** [comment]
Thanks @kesara !
